---
# sample configuration for MqttBridge. Changevalues to fit your configuration.
############################################################################
# INFO:
# - jsonplaceholder.com provides dummy rest endpoints for testing.
# - It is not possible to define custom callbacks in the yaml config to avoid
#   injection of malicious code.
# - Dynamic routes expect a valid request body as message payload.
mqttHost: 'mqtt://localhost'
routes:
  # this route will respond on the default topic example/topic/response
  example/topic/get:
    route: 'https://jsonplaceholder.typicode.com/albums/1'
    method: 'get'
  # this route will publish any response on custom/topic/response
  example/topic/custom/get:
    route: 'https://jsonplaceholder.typicode.com/albums/2'
    responseTopic: 'custom/topic/response'
    method: 'get'
  # example for post
  example/topic/post:
    route: 'https://jsonplaceholder.typicode.com/albums'
    method: 'post'
  # example for dynamic routing
  example/topic/dynamic:
    dynamic: true
